### ISSUE TITLE
Re-Implementing Git with Ruby

### ISSUE THREAD

**Issue by davekinkead** [BrisRuby/meetups#110]
Learning the fundamentals of anything is critical to understanding it but I found git extra hard because the most common commands - the porcelain - are conceptually very different to the data model - the plumbing.

It all became (a little) clearer however when I rolled my selves up and got down and dirty in git's data model and tried to commit, branch, and merge manually.  So I thought it might be fun/interesting/useful to dive into the sewers of git's plumbing and re-implement git with ruby, step by step.  Anybody keen?

**Comment by ghiculescu** [comment]
:+1:

**Comment by patrickgordon** [comment]
+1
I'm terrible at Git and it terrifies me.

**Comment by SorchaAbel** [comment]
+1

On 7 October 2015 at 12:06, Dave Kinkead <notifications@github.com> wrote:

> Learning the fundamentals of anything is critical to understanding it but
> I found git extra hard because the most common commands - the porcelain -
> are conceptually very different to the data model - the plumbing.
>
> It all became (a little) clearer however when I rolled my selves up and
> got down and dirty in git's data model and tried to commit, branch, and
> merge manually. So I thought it might be fun/interesting/useful to dive
> into the sewers of git's plumbing and re-implement git with ruby, step by
> step. Anybody keen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisRuby/meetups/issues/110>.
>



-- 
Sorcha Abel
IT Software Developer

T 07 3319 4430
E sorcha.abel@htw.com.au

Level 1, 811 Gympie Road, Chermside, QLD, 4032
PO Box 61, Chermside South, QLD, 4032

HERRON TODD WHITE | www.htw.com.au

-- 
Please consider the impact on the environment before you print this email

The information contained in this e-mail and any attachments are strictly 
private and confidential. This e-mail should only be read by the intended 
addressee. If you are not the intended addressee, you are strictly 
prohibited from using, reproducing, disclosing, or distributing the 
information contained herein and any attached files and/or documents. 
Unless stated otherwise, this email represents only the views of the sender 
and not the views of Herron Todd White. Before opening or using any files 
and/or attachments, we recommend you run your own virus protection, as 
although we will not knowingly transmit a virus, Herron Todd White accepts 
no liability for virus transmission. Liability limited by a scheme approved 
under Professional Standards Legislation. The scheme does not apply within 
Tasmania.

**Comment by gizotti** [comment]
:+1:

**Comment by RachelleOnRails** [comment]
:+1:  Git scares me too.

**Comment by tomjrob** [comment]
+1 Great Idea.

**Comment by hackling** [comment]
Dave, you are a sucker for punishment. :+1: +1

**Comment by davekinkead** [comment]
Turns out this was much harder than I thought :( But hey, it least I know way too much about git internals now...

**Comment by davekinkead** [comment]
Notes coming soon. Or soonish.

**Comment by nigelr** [comment]
Great talk @davekinkead was both an intro to GIT for people as well as seeing some of the backend intricacies

**Comment by SorchaAbel** [comment]
Thanks Dave, I thought it was a great talk :)

On 28 October 2015 at 11:09, Nigel Rausch <notifications@github.com> wrote:

> Great talk @davekinkead <https://github.com/davekinkead> was both an
> intro to GIT for people as well as seeing some of the backend intricacies
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisRuby/meetups/issues/110#issuecomment-151688757>.
>



-- 
Sorcha Abel
IT Software Developer

T 07 3319 4430
E sorcha.abel@htw.com.au

Level 1, 811 Gympie Road, Chermside, QLD, 4032
PO Box 61, Chermside South, QLD, 4032

HERRON TODD WHITE | www.htw.com.au

-- 
Please consider the impact on the environment before you print this email

The information contained in this e-mail and any attachments are strictly 
private and confidential. This e-mail should only be read by the intended 
addressee. If you are not the intended addressee, you are strictly 
prohibited from using, reproducing, disclosing, or distributing the 
information contained herein and any attached files and/or documents. 
Unless stated otherwise, this email represents only the views of the sender 
and not the views of Herron Todd White. Before opening or using any files 
and/or attachments, we recommend you run your own virus protection, as 
although we will not knowingly transmit a virus, Herron Todd White accepts 
no liability for virus transmission. Liability limited by a scheme approved 
under Professional Standards Legislation. The scheme does not apply within 
Tasmania.

**Comment by RachelleOnRails** [comment]
Thanks @davekinkead . I learned a lot about how git works under the hood and now I feel considerably less scared of it.

**Comment by patassetbuilders** [comment]
Hi Dave,
Great talk about what happens under the hood.
As an addendum

I  find that the GitHub Desktop for mac provides a good user experience, in
particular  local commits are very clear before making the changes to
remote repository. Great for newbies like me, reduces the number of
commands that have to be committed to memory.

That said, I also think the network graphic on the github website really
useful when there are multiple branches and users sharing the repository.

Once again thanks
Pat




Pat James
Managing Director | Asset Builders Pty Ltd | Agility Project Services Pty
Ltd | 042 305 1175
www.assetbuilders.com.au
www.project-portal.com.au

**Comment by davekinkead** [comment]
Thanks for the feedback!
