### ISSUE TITLE
Volt ⚡

### ISSUE THREAD

**Issue by elliotthilaire** [BrisRuby/meetups#111]
Following on from the discussion about comparing Volt and Lotus here:
https://github.com/BrisRuby/meetups/issues/86

I spent a day learning Volt http://voltframework.com/. It's quite different. I'm impressed and think it's worth it's own talk.

I'm keen to share and show it off.

**Comment by nigelr** [comment]
+1

**Comment by SorchaAbel** [comment]
sounds good

On 28 October 2015 at 11:02, Elliott Hilaire <notifications@github.com>
wrote:

> Following on from the discussion about comparing Volt and Lotus here:
> #86 <https://github.com/BrisRuby/meetups/issues/86>
>
> I spent a day learning Volt http://voltframework.com/. It's quite
> different. I'm impressed and think it's worth it's own talk.
>
> I'm keen to share and show it off.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisRuby/meetups/issues/111>.
>



-- 
Sorcha Abel
IT Software Developer

T 07 3319 4430
E sorcha.abel@htw.com.au

Level 1, 811 Gympie Road, Chermside, QLD, 4032
PO Box 61, Chermside South, QLD, 4032

HERRON TODD WHITE | www.htw.com.au

-- 
Please consider the impact on the environment before you print this email

The information contained in this e-mail and any attachments are strictly 
private and confidential. This e-mail should only be read by the intended 
addressee. If you are not the intended addressee, you are strictly 
prohibited from using, reproducing, disclosing, or distributing the 
information contained herein and any attached files and/or documents. 
Unless stated otherwise, this email represents only the views of the sender 
and not the views of Herron Todd White. Before opening or using any files 
and/or attachments, we recommend you run your own virus protection, as 
although we will not knowingly transmit a virus, Herron Todd White accepts 
no liability for virus transmission. Liability limited by a scheme approved 
under Professional Standards Legislation. The scheme does not apply within 
Tasmania.

**Comment by patassetbuilders** [comment]
Looks impressive - certainly like to hear more

**Comment by michael-harrison** [comment]
+1

**Comment by elliotthilaire** [comment]
I'm going to close this as I won't be able to demo.

Here is a summary:

I spent a day looking at Volt and made a supply and demand beer pricing app.
https://github.com/elliotthilaire/beer_market

Volt uses difference paradigms to Rails

   * You can read docs from top to bottom in a short period of time, I recommend this.
   * It's good for realtime apps.
   * Synchronization between client and server is automatic. 
   * Code is organized into components
   * Asynchronous, promises are a core concept to get your head around.
   * You don't need Javascript, you write the client code in Ruby.
   * Single API for storage (saving something in the database or on the client storage is the same API)

If you are curious. I do think it is worthwhile looking at.

I'm not sure about it's future as development as the project is looking for a new maintainer: https://github.com/voltrb/volt/issues/357
